%simName = 'Fba_kcat_x05';
bucketUrl = 's3://alexander.williams.1967383.wcpe.sagebase.org';
downloadCloudSimulationResults(...
    'simName', simName, ...
    'bucketUrl', bucketUrl, ...
    'localFolder', 'cloudOutput' ...
    );